<?php

/**
 * Danh mục SLA điều khiển bằng trang "Cấu hình SLA" (system-config.sla). Mọi mốc thời hạn / nhắc / phạt tự động
 * đọc ở đây qua App\Services\Sla\Sla, không đặt hằng số trong code. Mỗi mục:
 *  - value / unit: ngưỡng mặc định; Admin đổi được, lưu ở bảng sla_settings. unit: hours | days | count |
 *    time (giờ trong ngày, lưu số phút từ 00:00) | day_of_month (ngày 1–28 của tháng).
 *  - penalty: hết hạn có tự lập biên bản phạt không (biên bản pending → giải trình → CM/HT/Admin xác nhận → vào lương);
 *    null = SLA chỉ nhắc / chặn thao tác, không có biên bản (trang cấu hình ẩn ô phạt).
 *  - amount: mức phạt gợi ý (đ) ghi vào biên bản; 0 = người chốt quyết mức phạt. amount_label / amount_per (tuỳ chọn): nhãn ô này / mức tính theo (vd. 'ngày' trễ).
 *  - task: có tự giao việc cho người phụ trách khi mốc được kích hoạt.
 *  - switchable (tuỳ chọn, mặc định true): false = luôn áp dụng, trang cấu hình không có nút tắt (thời hạn chặn thao tác).
 *  - category (tuỳ chọn): loại lỗi của biên bản (Penalty::CATEGORIES) — quyết định ai chốt; mặc định 'operations'.
 */
return [
    'groups' => [
        'crm' => 'CRM & Tuyển sinh',
        'teacher' => 'Giáo viên & Trợ giảng',
        'big_test' => 'Big Test',
        'academic' => 'Học thuật & Dự án',
        'operations' => 'Vận hành & Học phí',
    ],

    /** Bậc phạt theo số lần tái phạm cộng dồn trong N tháng (system_settings sla.ladder_reset_months). */
    'ladder_reset_months' => 12,

    'rules' => [
        'crm.first_contact' => [
            'group' => 'crm',
            'label' => 'Liên hệ khách mới lần đầu',
            'description' => 'Kể từ lúc thêm khách, người phụ trách (Học vụ) phải liên hệ khách (gọi / nhắn / gặp, liên hệ được) hoặc chuyển trạng thái. Trễ → biên bản phạt cho người phụ trách + báo Admin.',
            'value' => 24,
            'unit' => 'hours',
            'penalty' => true,
            'amount' => 0,
            'task' => false,
            'violation' => 'Quá hạn SLA liên hệ khách mới',
        ],
        'crm.status_move' => [
            'group' => 'crm',
            'label' => 'Chuyển trạng thái chăm sóc tối đa',
            'description' => 'Kể từ lúc thêm khách, tối đa số giờ này phải chuyển khách khỏi trạng thái "Mới". Trễ → biên bản phạt + báo Admin.',
            'value' => 36,
            'unit' => 'hours',
            'penalty' => true,
            'amount' => 0,
            'task' => false,
            'violation' => 'Quá hạn SLA chuyển trạng thái chăm sóc khách',
        ],
        'crm.follow_up' => [
            'group' => 'crm',
            'label' => 'Chăm sóc tiếp theo',
            'description' => 'Khách đang chăm sóc (đã liên hệ, tư vấn → gửi kết quả) không có hoạt động chăm sóc nào trong số ngày này → cảnh báo Admin / Quản lý và người phụ trách; đồng hồ SLA trên danh sách khách chuyển "Quá hạn". Không phạt.',
            'value' => 3,
            'unit' => 'days',
            'penalty' => null,
            'amount' => 0,
            'task' => false,
            'violation' => 'Khách bị bỏ quên chăm sóc',
        ],
        'crm.test_result' => [
            'group' => 'crm',
            'label' => 'Trả kết quả test đầu vào',
            'description' => 'Từ lúc khách nộp bài test, tự giao việc "Trả kết quả test" cho người phụ trách; phải ghi nhận đã gửi kết quả trong thời hạn này. Trễ → biên bản phạt + báo Admin.',
            'value' => 24,
            'unit' => 'hours',
            'penalty' => true,
            'amount' => 0,
            'task' => true,
            'violation' => 'Quá hạn SLA trả kết quả test đầu vào',
        ],
        'crm.trial_feedback' => [
            'group' => 'crm',
            'label' => 'Phản hồi sau buổi học thử',
            'description' => 'Từ lúc buổi học thử kết thúc, tự giao việc "Phản hồi phụ huynh sau học thử" cho người phụ trách; phải liên hệ phụ huynh trong thời hạn này. Trễ → biên bản phạt + báo Admin.',
            'value' => 24,
            'unit' => 'hours',
            'penalty' => true,
            'amount' => 0,
            'task' => true,
            'violation' => 'Quá hạn SLA phản hồi sau học thử',
        ],
        'crm.tuition_followup' => [
            'group' => 'crm',
            'label' => 'Theo dõi thu học phí tuần đầu',
            'description' => 'Từ lúc chốt / chờ xếp lớp, tự giao việc theo dõi học phí cho người phụ trách; học phí phải thu đủ trong thời hạn này. Quá hạn → báo Admin (mặc định không tự phạt).',
            'value' => 168,
            'unit' => 'hours',
            'penalty' => false,
            'amount' => 0,
            'task' => true,
            'violation' => 'Quá hạn thu học phí tuần đầu sau khi chốt',
        ],
        'crm.failed_contacts' => [
            'group' => 'crm',
            'label' => 'Liên hệ thất bại liên tiếp',
            'description' => 'Sau số lần liên hệ không được liên tiếp này (gọi / nhắn / hình thức bất kỳ), hệ thống cảnh báo Admin và giao việc báo cáo cho người phụ trách. Không phạt.',
            'value' => 3,
            'unit' => 'count',
            'penalty' => false,
            'amount' => 0,
            'task' => true,
            'violation' => 'Liên hệ khách thất bại liên tiếp',
        ],

        'gv.remarks_late' => [
            'group' => 'teacher',
            'label' => 'Nhận xét sau buổi học (GV)',
            'description' => 'Sau khi buổi học kết thúc, GV phải gửi nhận xét buổi học (nội dung bài, bài tập, nhận xét học viên) trong thời hạn này. Trễ → biên bản cho GV theo bậc phạt tái phạm (Quy chế GV mục 4: lần 1 nhắc nhở, lần 2 phạt 30.000đ, từ lần 3 phạt 60.000đ).',
            'value' => 12,
            'unit' => 'hours',
            'penalty' => true,
            'amount' => 0,
            'ladder' => [0, 30000, 60000],
            'task' => false,
            'violation' => 'Gửi nhận xét sau buổi học trễ',
        ],

        'gv.checkin_window' => [
            'group' => 'teacher',
            'label' => 'Hạn chấm công dạy (check-in)',
            'description' => 'GV phải check-in buổi dạy trong số giờ này kể từ giờ bắt đầu buổi; quá hạn GV không tự check-in được (mất công trừ khi Học vụ xác nhận). Hệ thống cảnh báo GV khi còn dưới 15 phút.',
            'value' => 24,
            'unit' => 'hours',
            'penalty' => null,
            'amount' => 0,
            'task' => false,
            'switchable' => false,
            'violation' => 'Quá hạn chấm công dạy',
        ],
        'gv.attendance_window' => [
            'group' => 'teacher',
            'label' => 'Cửa sổ điểm danh học viên của GV',
            'description' => 'GV chỉ điểm danh học viên được trong khoảng ± số giờ này quanh giờ bắt đầu buổi (Học vụ có quyền điểm danh mọi lúc thì không giới hạn).',
            'value' => 24,
            'unit' => 'hours',
            'penalty' => null,
            'amount' => 0,
            'task' => false,
            'switchable' => false,
            'violation' => 'Quá hạn điểm danh học viên',
        ],

        'big_test.paper_reminder' => [
            'group' => 'big_test',
            'label' => 'Nhắc lịch thi & duyệt đề',
            'description' => 'Trước ngày thi số ngày này: nhắc GV chính / GVNN / trợ giảng lịch thi (1 lần); đề chưa phân phối thì nhắc Học thuật mỗi ngày và tự giao việc "Duyệt & phân phối đề" (hạn = ngày thi, tự đóng khi phân phối). Cũng là khoảng nhắc khi chặng có ngày dự kiến Big Test mà chưa có đợt thi.',
            'value' => 7,
            'unit' => 'days',
            'penalty' => null,
            'amount' => 0,
            'task' => true,
            'violation' => 'Big Test chưa duyệt đề',
        ],
        'big_test.paper_approval' => [
            'group' => 'big_test',
            'label' => 'Hạn duyệt & phân phối đề',
            'description' => 'Học thuật phải duyệt & phân phối đề trước ngày thi ít nhất số ngày này; sau mốc này thông báo đổi thành "Quá hạn duyệt đề". Hạn xử lý của order đề = ngày thi trừ số ngày này.',
            'value' => 3,
            'unit' => 'days',
            'penalty' => null,
            'amount' => 0,
            'task' => false,
            'switchable' => false,
            'violation' => 'Quá hạn duyệt đề Big Test',
        ],
        'big_test.paper_missing' => [
            'group' => 'big_test',
            'label' => 'GV chưa nhận đề sát giờ thi',
            'description' => 'Còn dưới số giờ này tới giờ thi mà đề chưa được phân phối → mỗi người duyệt Big Test (Học thuật, không tính Admin) 1 biên bản. Tắt tự lập biên bản thì chỉ thông báo.',
            'value' => 24,
            'unit' => 'hours',
            'penalty' => true,
            'amount' => 0,
            'task' => false,
            'category' => 'academic',
            'violation' => 'GV chưa nhận đề Big Test sát ngày thi',
        ],
        'big_test.results_late' => [
            'group' => 'big_test',
            'label' => 'Trả kết quả Big Test cho phụ huynh',
            'description' => 'Kết quả phải được duyệt & gửi phụ huynh đủ cả lớp trong số ngày này kể từ ngày thi. Trễ → 1 biên bản / đợt thi, mức phạt = mức gợi ý × số ngày trễ, cập nhật mỗi ngày tới khi gửi đủ. Còn thiếu điểm → GV chính chịu; đã nhập đủ, chờ duyệt / gửi → người duyệt Big Test đầu tiên.',
            'value' => 7,
            'unit' => 'days',
            'penalty' => true,
            'amount' => 50000,
            'amount_label' => 'Mức phạt gợi ý mỗi ngày trễ',
            'amount_per' => 'ngày',
            'task' => false,
            'category' => 'academic',
            'violation' => 'Trả kết quả Big Test trễ',
        ],

        'academic.milestone_late' => [
            'group' => 'academic',
            'label' => 'Trễ mốc dự án học thuật',
            'description' => 'Dự án soạn sách / chương trình đã chốt tiến độ: mốc chưa hoàn thành khi qua 23:59 ngày hạn cộng số giờ ân hạn này → biên bản cho người nhận mốc (chưa có người nhận thì người phụ trách dự án), Học thuật / Admin xác nhận mới tính vào lương. Trước hạn 24 giờ hệ thống nhắc người nhận mốc.',
            'value' => 1,
            'unit' => 'hours',
            'penalty' => true,
            'amount' => 0,
            'task' => false,
            'category' => 'academic',
            'violation' => 'Trễ deadline mốc dự án học thuật',
        ],
        'academic.milestone_remind' => [
            'group' => 'academic',
            'label' => 'Nhắc mốc dự án học thuật sắp tới hạn',
            'description' => 'Trước hạn mốc dự án số giờ này, hệ thống nhắc người nhận mốc (1 lần / mốc).',
            'value' => 24,
            'unit' => 'hours',
            'penalty' => null,
            'amount' => 0,
            'task' => false,
            'violation' => 'Mốc dự án học thuật sắp tới hạn',
        ],
        'syllabus.adjustment_approval' => [
            'group' => 'academic',
            'label' => 'Duyệt yêu cầu giãn tiến độ giáo trình',
            'description' => 'Yêu cầu giãn tiến độ phải được duyệt trong số ngày này; quá hạn → báo người duyệt 1 lần.',
            'value' => 3,
            'unit' => 'days',
            'penalty' => null,
            'amount' => 0,
            'task' => false,
            'violation' => 'Quá hạn duyệt giãn tiến độ',
        ],
        'material.monthly_deadline' => [
            'group' => 'academic',
            'label' => 'Hạn order GVNN / học liệu học thuật',
            'description' => 'Order GVNN và học liệu học thuật xử lý đầu tháng: hạn là 23:59 ngày này của tháng chứa ngày sử dụng. Quá hạn → order "Quá hạn" + báo người xử lý. Áp dụng cho order tạo sau khi lưu.',
            'value' => 5,
            'unit' => 'day_of_month',
            'penalty' => null,
            'amount' => 0,
            'task' => false,
            'switchable' => false,
            'violation' => 'Order học liệu quá hạn',
        ],
        'material.day_before_cutoff' => [
            'group' => 'academic',
            'label' => 'Giờ chốt order đạo cụ / in ấn',
            'description' => 'Order đạo cụ / in ấn: Học vụ xử lý trước giờ này của ngày hôm trước ngày sử dụng. Quá hạn → order "Quá hạn" + báo người xử lý. Áp dụng cho order tạo sau khi lưu.',
            'value' => 15 * 60,
            'unit' => 'time',
            'penalty' => null,
            'amount' => 0,
            'task' => false,
            'switchable' => false,
            'violation' => 'Order học liệu quá hạn',
        ],

        'care.first_month' => [
            'group' => 'operations',
            'label' => 'Chăm sóc học viên tháng đầu',
            'description' => 'Mốc Buổi 1 / Buổi 4–5 có hạn sau buổi học số ngày này (mốc Đủ 30 ngày: hạn đúng ngày). Việc chăm sóc quá hạn mà chưa tick bên CRM → biên bản cho Học vụ được giao.',
            'value' => 1,
            'unit' => 'days',
            'penalty' => true,
            'amount' => 0,
            'task' => true,
            'violation' => 'Quá hạn SLA chăm sóc học viên tháng đầu',
        ],
        'tuition.cash_deposit' => [
            'group' => 'operations',
            'label' => 'Nộp tiền mặt về TK công ty',
            'description' => 'Tiền mặt thu trong ngày phải được xác nhận nộp về tài khoản công ty trước giờ này cùng ngày; quá giờ → nhắc người thu và người có quyền xác nhận. Không tự phạt.',
            'value' => 19 * 60,
            'unit' => 'time',
            'penalty' => null,
            'amount' => 0,
            'task' => false,
            'violation' => 'Tiền mặt chưa nộp về TK công ty',
        ],
        'tuition.refund_processing' => [
            'group' => 'operations',
            'label' => 'Xử lý hoàn phí / chuyển nhượng',
            'description' => 'Hồ sơ hoàn phí / chuyển nhượng phải xử lý trong số ngày này và không quá cuối tháng lập hồ sơ; còn ≤ 1 ngày hoặc quá hạn → nhắc người duyệt mỗi ngày.',
            'value' => 7,
            'unit' => 'days',
            'penalty' => null,
            'amount' => 0,
            'task' => false,
            'violation' => 'Quá hạn xử lý hoàn phí / chuyển nhượng',
        ],
        'penalty.payment_due' => [
            'group' => 'operations',
            'label' => 'Hạn nộp phạt',
            'description' => 'Biên bản đã chốt mức phạt phải nộp trong số ngày này; hệ thống nhắc ngày trước hạn và đúng hạn, quá hạn chưa nộp thì trừ lương.',
            'value' => 2,
            'unit' => 'days',
            'penalty' => null,
            'amount' => 0,
            'task' => false,
            'switchable' => false,
            'violation' => 'Quá hạn nộp phạt',
        ],
        'penalty.record_window' => [
            'group' => 'operations',
            'label' => 'Thời hạn lập biên bản vi phạm',
            'description' => 'Biên bản vi phạm chỉ lập được cho lỗi xảy ra trong số giờ gần nhất này (không lùi ngày quá xa, kể cả Admin).',
            'value' => 24,
            'unit' => 'hours',
            'penalty' => null,
            'amount' => 0,
            'task' => false,
            'switchable' => false,
            'violation' => 'Quá hạn lập biên bản',
        ],
        'payroll.close_after' => [
            'group' => 'operations',
            'label' => 'Chốt công & lỗi sau cuối tháng',
            'description' => 'Chốt công và chốt lỗi kéo dài tới hết ngày cuối tháng + số ngày này; chỉ sau mốc đó mới duyệt (chốt) bảng lương, kể cả Admin.',
            'value' => 2,
            'unit' => 'days',
            'penalty' => null,
            'amount' => 0,
            'task' => false,
            'switchable' => false,
            'violation' => 'Chốt bảng lương trước hạn',
        ],
        'hr.contract_warning' => [
            'group' => 'operations',
            'label' => 'Cảnh báo hợp đồng sắp hết hạn',
            'description' => 'Hợp đồng nhân sự hết hạn trong số ngày này → cảnh báo (1 lần / hợp đồng) và đánh dấu "Sắp hết hạn" trên danh sách người dùng.',
            'value' => 30,
            'unit' => 'days',
            'penalty' => null,
            'amount' => 0,
            'task' => false,
            'violation' => 'Hợp đồng sắp hết hạn',
        ],
        'stock.restock_task' => [
            'group' => 'operations',
            'label' => 'Nhập bù sách / hàng hết tồn',
            'description' => 'Kho chi nhánh hết hoặc âm tồn → tự giao Admin việc nhập bù với hạn số ngày này.',
            'value' => 2,
            'unit' => 'days',
            'penalty' => null,
            'amount' => 0,
            'task' => true,
            'switchable' => false,
            'violation' => 'Chưa nhập bù tồn kho',
        ],
    ],
];
