<x-app-layout>
    <x-slot name="header"><div><h1 class="text-xl font-bold">Xếp lịch & theo dõi phụ đạo</h1><p class="text-xs text-gray-500">Từ học viên cần bổ trợ đến buổi dạy bù và bảng công chờ duyệt</p></div></x-slot>
    <div class="grid lg:grid-cols-3 gap-6">
        <form method="POST" action="{{ route('tasks.support-sessions.store') }}" class="bg-white border rounded-2xl p-5 space-y-3">@csrf
            <h2 class="font-bold text-sm">Xếp buổi phụ đạo</h2>
            <select name="class_report_student_support_id" class="w-full text-xs rounded-lg border-gray-200"><option value="">Từ báo cáo trực lớp (không bắt buộc)</option>@foreach($pendingSupports as $support)<option value="{{ $support->id }}">{{ $support->student?->name }} · {{ $support->reason }}</option>@endforeach</select>
            <select name="class_id" required class="w-full text-xs rounded-lg border-gray-200"><option value="">Chọn lớp</option>@foreach($classes as $class)<option value="{{ $class->id }}">{{ $class->name }}</option>@endforeach</select>
            <select name="student_id" required class="w-full text-xs rounded-lg border-gray-200"><option value="">Chọn học viên</option>@foreach($classes as $class)@foreach($class->students as $student)<option value="{{ $student->id }}">{{ $student->name }} · {{ $class->name }}</option>@endforeach @endforeach</select>
            <select name="teacher_id" required class="w-full text-xs rounded-lg border-gray-200"><option value="">Chọn giáo viên</option>@foreach($teachers as $teacher)<option value="{{ $teacher->id }}">{{ $teacher->name }}</option>@endforeach</select>
            <div class="grid grid-cols-3 gap-2"><input type="date" name="session_date" value="{{ now()->addDay()->format('Y-m-d') }}" required class="text-xs rounded-lg border-gray-200"><input type="time" name="start_time" required class="text-xs rounded-lg border-gray-200"><input type="time" name="end_time" required class="text-xs rounded-lg border-gray-200"></div>
            <input name="room" placeholder="Phòng" class="w-full text-xs rounded-lg border-gray-200"><textarea name="reason" placeholder="Mục tiêu phụ đạo" class="w-full text-xs rounded-lg border-gray-200"></textarea>
            <button class="w-full bg-primary text-white rounded-lg py-2 text-xs font-bold">Xếp lịch</button>
        </form>
        <div class="lg:col-span-2 bg-white border rounded-2xl overflow-hidden"><table class="w-full text-xs"><thead class="bg-gray-50"><tr><th class="p-3 text-left">Học viên</th><th class="p-3">Lịch</th><th class="p-3">Giáo viên</th><th class="p-3">Trạng thái</th><th class="p-3"></th></tr></thead><tbody class="divide-y">@forelse($sessions as $session)<tr><td class="p-3 font-bold">{{ $session->student?->name }}<small class="block text-gray-400">{{ $session->classModel?->name }}</small></td><td class="p-3 text-center">{{ $session->session_date->format('d/m/Y') }}<br>{{ $session->start_time }}-{{ $session->end_time }}</td><td class="p-3 text-center">{{ $session->teacher?->name }}</td><td class="p-3 text-center">{{ $session->status }}</td><td class="p-3">@if($session->status !== 'completed')<form method="POST" action="{{ route('tasks.support-sessions.complete', $session->id) }}">@csrf<button class="text-emerald-700 font-bold">Hoàn thành</button></form>@endif</td></tr>@empty<tr><td colspan="5" class="p-8 text-center text-gray-400">Chưa có lịch phụ đạo.</td></tr>@endforelse</tbody></table></div>
    </div>
</x-app-layout>
